services:
  client:
    container_name: debug_dev_client
    build: ./client
    image: debug_client
    ports: 
      - 8080:8080
    working_dir: /code
    volumes:
      - type: bind
        source: ./client
        target: /server
    command: [ "http-server" ]
  api:
    container_name: debug_dev_api
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - PGUSER=futureproof
      - PGHOST=db
      - PGPASSWORD=futurebook_password
      - PGDATABASE=futurebook
      - PGPORT=5432
    depends_on:
      - db
    command: bash -c "npm install && npm run seedDev && npm run dev"
  db:
    container_name: debug_dev_db
    expose:
      - "5432"
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    environment:
      - POSTGRES_DB=futurebook
      - POSTGRES_USER=futureproof
      - POSTGRES_PASSWORD=futurebook_password
volumes:
  dbdata:
networks: 
  default:
    name: debug_api
